//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class agdConvite
    {
        public int agdConviteID { get; set; }
        public int agdContatoIDConvidado { get; set; }
        public int agdContatoIDEmissor { get; set; }
        public int agdEventoID { get; set; }
        public System.DateTime acvDataHoraEnvio { get; set; }
        public bool acvConfirmado { get; set; }
    
        public virtual agdContato agdContato { get; set; }
        public virtual agdContato agdContato1 { get; set; }
        public virtual agdEvento agdEvento { get; set; }
    }
}
