//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class agdContato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agdContato()
        {
            this.agdConvite = new HashSet<agdConvite>();
            this.agdConvite1 = new HashSet<agdConvite>();
            this.agdEvento = new HashSet<agdEvento>();
        }
    
        public int agdContatoID { get; set; }
        public Nullable<int> agdUsuarioID { get; set; }


        [Display(Name = "Contato")]
        [Required(ErrorMessage = "Esse campo é obrigatório")]
        [StringLength(100, ErrorMessage = "O campo deve conter no máximo 100 caracteres!!")]
        public string actNome { get; set; }

        [Display(Name = "Sexo")]
        [Required(ErrorMessage = "Esse campo é obrigatório")]
        public bool actSexo { get; set; }


        public string actTelefone { get; set; }

        [Display(Name = "Data de Nascimento")]
        [Required(ErrorMessage = "Esse campo é obrigatório")]
        public System.DateTime actDataNascimento { get; set; }

        [Display(Name = "Endereço Residencial")]
        public string actEndereco { get; set; }

        [Display(Name = "Foto")]
        public string actFoto { get; set; }

        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Endereço de Email Invalido!!")]
        [StringLength(254, ErrorMessage = "O campo deve conter no máximo 254 caracteres!!")]
        public string actEmail { get; set; }
    
        public virtual agdUsuario agdUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agdConvite> agdConvite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agdConvite> agdConvite1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agdEvento> agdEvento { get; set; }
    }
}
