//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class agdContato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agdContato()
        {
            this.agdConvite = new HashSet<agdConvite>();
            this.agdConvite1 = new HashSet<agdConvite>();
            this.agdEvento = new HashSet<agdEvento>();
        }
    
        public int agdContatoID { get; set; }
        public Nullable<int> agdUsuarioID { get; set; }
        public string actNome { get; set; }
        public bool actSexo { get; set; }
        public string actTelefone { get; set; }
        public System.DateTime actDataNascimento { get; set; }
        public string actEndereco { get; set; }
        public string actFoto { get; set; }
        public string actEmail { get; set; }
    
        public virtual agdUsuario agdUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agdConvite> agdConvite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agdConvite> agdConvite1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agdEvento> agdEvento { get; set; }
    }
}
