//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class agdEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agdEvento()
        {
            this.agdConvite = new HashSet<agdConvite>();
        }

        public int agdEventoID { get; set; }
        public int agdContatoID { get; set; }

        [Display(Name = "Evento")]
        [Required(ErrorMessage = "Esse campo é obrigatório")]
        [StringLength(100, ErrorMessage = "O campo deve conter no máximo 100 caracteres!!")]
        public string aevNome { get; set; }

        [Display(Name = "Foto")]
        public string aevFoto { get; set; }

        [Display(Name = "Data/Hora do Evento")]
        [Required(ErrorMessage = "Esse campo é obrigatório")]
        public System.DateTime aevDataHora { get; set; }

        [Display(Name = "Local do Evento")]
        [Required(ErrorMessage = "Esse campo é obrigatório")]
        public string aevLocal { get; set; }


        public string aevDescricao { get; set; }


        public int agdCategoriaEventoID { get; set; }

        public virtual agdCategoriaEvento agdCategoriaEvento { get; set; }
        public virtual agdContato agdContato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agdConvite> agdConvite { get; set; }
    }
}