//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class agdEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agdEvento()
        {
            this.agdConvite = new HashSet<agdConvite>();
        }
    
        public int agdEventoID { get; set; }
        public int agdContatoID { get; set; }
        public string aevNome { get; set; }
        public string aevFoto { get; set; }
        public System.DateTime aevDataHora { get; set; }
        public string aevLocal { get; set; }
        public string aevDescricao { get; set; }
        public int agdCategoriaEventoID { get; set; }
    
        public virtual agdCategoriaEvento agdCategoriaEvento { get; set; }
        public virtual agdContato agdContato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agdConvite> agdConvite { get; set; }
    }
}
