//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class agdUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agdUsuario()
        {
            this.agdContato = new HashSet<agdContato>();
        }
    
        public int agdUsuarioID { get; set; }
        public string ausEmail { get; set; }
        public string ausSenha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agdContato> agdContato { get; set; }
    }
}
