//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AgendaProvaEvoluaEntities1 : DbContext
    {
        public AgendaProvaEvoluaEntities1()
            : base("name=AgendaProvaEvoluaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agdCategoriaEvento> agdCategoriaEvento { get; set; }
        public virtual DbSet<agdContato> agdContato { get; set; }
        public virtual DbSet<agdEvento> agdEvento { get; set; }
        public virtual DbSet<agdUsuario> agdUsuario { get; set; }
    
        public virtual int sp_insereUsuario(Nullable<int> contatoID, string email, string senha)
        {
            var contatoIDParameter = contatoID.HasValue ?
                new ObjectParameter("contatoID", contatoID) :
                new ObjectParameter("contatoID", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var senhaParameter = senha != null ?
                new ObjectParameter("senha", senha) :
                new ObjectParameter("senha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insereUsuario", contatoIDParameter, emailParameter, senhaParameter);
        }
    }
}
